Add permissive LICENSE.md
ipfs/service-worker-gateway pull request #154
Opened 2024-03-25 17:18 UTC by 2color

Fixes #116

2024-03-26 12:16 UTC, SgtPooki commented
We should use the same pattern as libp2p with two license files

2024-03-26 13:19 UTC, lidel requested changes
@2color thanks! just small concern around making this repo a special snowflake with different LICENSE than Kubo and Helia.

2024-03-26 13:19 UTC, lidel commented on LICENSE.md
@2color any reason why we used different syntax than we have in Kubo and Helia repos?

I was under impression we want to copy&paste:
- https://github.com/ipfs/helia/blob/main/LICENSE (we could add SPDX tags here and in README)
- https://github.com/ipfs/helia/blob/main/LICENSE-MIT
- https://github.com/ipfs/helia/blob/main/LICENSE-APACHE

2024-03-26 15:11 UTC, aschmahmann commented on LICENSE.md
We can use a single one, no https://github.com/ipfs/ipfs-repository-template/blob/c0e7956eae1c7541e11fc24c24058085fc8f3339/LICENSE.md? If not should we change the repo template?

2024-03-26 21:14 UTC, SgtPooki commented on LICENSE.md
js-libp2p and helia have been using separate ones for a while, we should stick to that pattern.

2024-03-27 11:39 UTC, 2color commented on LICENSE.md
I don't have strong opinions. I also don't want to waste time on this.

I've stuck to the same convention as Helia and added the SPDX tag in the `LICENSE` file. 

Hopefully that should keep everyone happy.

2024-03-27 14:16 UTC, SgtPooki approved these changes

2024-03-27 14:16 UTC, merged

2024-03-27 14:17 UTC, SgtPooki commented
@lidel, what should we do for the dev sign-off process for previous committers?

2024-03-27 14:39 UTC, 2color commented
I think we can just continue collecting approvals here. 

@lidel @whizzzkid @lidel @achingbrain @MarcoPolo @aschmahmann 

Can you please review this and approve to confirm you are ok with the license update?

2024-03-27 15:03 UTC, lidel reviewed
I accept these license terms.

ps. we should get approvals before merging, but as long everyone replies here we are good and don't have to revert :)

2024-03-27 17:08 UTC, SgtPooki commented
I accept these license terms.

2024-03-27 17:15 UTC, aschmahmann commented
I accept these license terms.

2024-03-27 17:17 UTC, whizzzkid commented
I accept these license terms.

2024-03-27 18:21 UTC, achingbrain commented
I accept these license terms.

2024-03-27 18:22 UTC, achingbrain commented on LICENSE.md
Urgh, what a pain.  aegir-managed projects should be using these files: https://github.com/ipfs/aegir/tree/master/src/check-project/files which I think were taken from go-ipfs in the dim and distant past.  I may be wrong, memory is a funny thing.

2024-03-27 19:21 UTC, SgtPooki commented
just need Marco and I think we're good

2024-03-27 20:07 UTC, MarcoPolo commented
I accept these license terms.

2024-03-28 09:53 UTC, 2color commented on LICENSE.md
@achingbrain what implication does it have if the license files are different?

For example, in this repo I added the `SPDX-License-Identifier: Apache-2.0 OR MIT` tag.