Make routers optional and enable local insecure gateways
ipfs/service-worker-gateway pull request #303
Opened 2024-06-19 16:11 UTC by 2color

## Description

This PR:
- makes routers optional, since they are not a requirement. 
- Enables insecure (not and local gateways as discussed in https://github.com/ipfs/service-worker-gateway/issues/299#issuecomment-2178733067 

## Notes & open questions

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-06-20 01:00 UTC, lidel requested changes
Did not run it locally yet, but dropping quick feedback / questions in the meantime.

2024-06-20 01:00 UTC, lidel commented on src/lib/local-gateway.ts
> +export const localGwUrl = 'http://127.0.0.1:8080'
Since we know it is not subdomains fault, we may want to switch to `localhost` which is Secure Context:

```suggestion
export const localGwUrl = 'http://localhost:8080'
```

Should be fine, as long  `fetch` follows redirects by default, or is there more to it?

2024-06-20 01:00 UTC, lidel commented on src/lib/config-db.ts
> +export const defaultRouters = []
If we remove default delegated router, won't we lose opportunistic  direct retrieval over HTTP? Maybe keeping the default as-is is better play for Camp?

Rationale: 

It seems to work out-of-the-box thanks to session changes in Helia a while ago. Right now it is mostly web3.storage, but a lot of data is there.

You can test with `bafkreibm6jg3ux5qumhcn2b3flc3tyu6dmlb4xa7u5bf44yegnrjhc4yeq`

Example: https://delegated-ipfs.dev/routing/v1/providers/bafkreibm6jg3ux5qumhcn2b3flc3tyu6dmlb4xa7u5bf44yegnrjhc4yeq  returns `/dns/data.filstorage.io/tcp/443/https` (fails, due to basic-auth) and `/dns4/dag.w3s.link/tcp/443/https` (open) so the block is likely fetched from `dag.w3s.link`.

2024-06-20 01:00 UTC, lidel commented on src/pages/config.tsx
> +            gwConf.push(localGwUrl)
nit: prepend to the list, so localhost is prioritized
```suggestion
            gwConf.unshift(localGwUrl)
```

2024-06-20 08:54 UTC, 2color commented on src/lib/local-gateway.ts
> +export const localGwUrl = 'http://127.0.0.1:8080'
Based on https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts 127.0.0.1 should also be Secure Context. 

Is there any particular benefit to using localhost. We don't change the `redirect` config in fetch, so it's follow, and indeed it is followed.  

I don't have a strong opinion, just curious why localhost is preferred.

2024-06-20 09:04 UTC, 2color commented on src/lib/config-db.ts
> +export const defaultRouters = []
> If we remove default delegated router, won't we lose opportunistic direct retrieval over HTTP? 

That's correct. 

> Maybe keeping the default as-is is better play for Camp?

In #288 you proposed disabling it by default. 


It should be disabled by default, until we have direct retrieval working

2024-06-20 14:41 UTC, lidel commented on src/lib/config-db.ts
> +export const defaultRouters = []
Yeah, let's keep it, I wrote that before I realized we do have direct retrieval over http if http multiaddr is present.

2024-06-20 14:51 UTC, 2color commented
I'm currently blocked by a bug I found, where verifiedFetch does not respect the `allowInsecure` and `allowLocal` config options passed to it.

I have a reproduction here: https://codepen.io/2color/pen/VwOXeMz. But I haven't been able to find out where the root of the problem is. Still digging into this.

2024-06-28 18:05 UTC, lidel requested changes
We don't have testing in place for this, so each flow needs to be inspected manually.
I did some testing in vanilla Google Chrome (empty profile each time) and both need a bit more polish.

- **Localhost detection** works only when dancing a specific way:
  - 🟢 Works when visiting the main domain first (`http://test1.localhost:3000/`) and then manually open config  detects and prepends my `localhost:8080` gateway, and uses it just fine
  - 🚧 Does not work when visiting the main domain first with config URL opened (`http://test2.localhost:3000/#/ipfs-sw-config`) 
  - 🚧 Does not work if I visit subdomain first (`http://specs-ipfs-tech.ipns.test3.localhost:3000/` does not prepend localhost)
  - ⭕ The detection does dot work in Brave because they have very strick adblock (Brave Shields) rules: 
    > ![2024-06-28_19-58](https://github.com/ipfs/service-worker-gateway/assets/157609/4e59f616-dc3e-45a0-be0e-a30c5a91ac6b)  
    Due to this, a big chunk of audience won't be able to benefit from this anyway :disappointed: 
- **Disabling delegated routing** works, but does more harm than good, making it not useful:
  - 🚧 Disabling delegated routing breaks DNSLink resolution ([example](https://github.com/ipfs/service-worker-gateway/assets/157609/6b66a431-6b08-4a63-b8e1-e92d4740cd26)), while it should only impact IPNS and not DNSLink

-----

Between localhost detection and adjusting  things in https://github.com/ipshipyard/waterworks-infra/issues/55 the latter improves things in all browsers, so we may want to park this and focus on that + the other quality-of-life improvements from the Camp milestone.

I feel we will get back to this once we simplify codebase after Camp. Right now, too much of a time sink.

2024-06-28 18:53 UTC, SgtPooki commented on src/lib/local-gateway.ts
> +export const localGwUrl = 'http://127.0.0.1:8080'
I don't think there's any more to it for most usecases.

2024-10-24 21:28 UTC, SgtPooki commented
@2color I created https://github.com/ipfs/service-worker-gateway/pull/403 to replace this one. Closing

2024-10-24 21:28 UTC, closed without merging