chore: gzip compression only on prod builds
ipfs/service-worker-gateway pull request #97
Opened 2024-03-08 22:37 UTC by SgtPooki

- dont gzip html files

## Title

Gzip compression for prod builds only.

## Description

- Moves compression plugin to prod config only.
- Removes compression for webpack-dev-server (should speed up dev builds).
- removes html files from compression

related to #96 & #93

## Notes & open questions

### Notes
FYSI, my nginx config required the following changes:

1. `gzip_static on;` to serve pre-compressed files
2. building nginx with `--with-http_gzip_static_module` to enable serving pre-compressed files
    - `brew tap denji/nginx`
    - `brew install nginx-full --with-http_gzip_static_module`

- [ ] For IPFS hosted sites, we likely need to add some entries:
    - `/*.js /:splat.js.gz 301`
    - `/:splat.css /:splat.css.gz 301`

### Questions

- [ ] does anyone see any issues with this approach?
- [ ] are the splat entries above correct?

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-03-08 22:41 UTC, SgtPooki commented on webpack.config.js
> +      deleteOriginalAssets: true
`deleteOriginalAssets` was in the wrong location (inside `compressionOptions`) previously.

2024-03-09 00:03 UTC, SgtPooki commented
ok.. for testing redirects locally, taken from https://github.com/ipfs/kubo/blob/e22f47ae4b4d83cf5e3f1c901c10905ebd69d492/test/sharness/t0109-gateway-web-_redirects.sh#L3

```

test_should_contain() {
  test "$#" = 2 || error "bug in the test script: not 2 parameters to test_should_contain"
  if ! grep -q "$1" "$2"
  then
    echo "'$2' does not contain '$1', it contains:"
    cat "$2"
    return 1
  fi
}
```

we can do the following with a locally running kubo node:

```
> npm run clean && npm run build && ls dist && CID=$(npx kubo add --cid-version 1 -Qr dist)
> curl -sD - "http://127:0.0.1:8081/ipfs/$CID/config" > response  &&
  test_should_contain "302 Moved Permanently" response
```

and it will fail if the redirect doesn't match.

2024-03-09 00:38 UTC, SgtPooki commented
Before merging from main (with all the updates from #89 and others)

<img width="343" alt="image" src="https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/1173416/f3b1d20b-d058-4c06-82fe-10421e3cfa18">

After merging from main:

<img width="352" alt="image" src="https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/1173416/959052ea-6d6c-4d1d-ba98-8dd87604c93d">

2024-03-09 00:57 UTC, SgtPooki commented
without node-polyfills-plugin (https://github.com/ipfs-shipyard/helia-service-worker-gateway/pull/97/commits/78a564fc0bf15fe79bdd4845f21c4a1d95eb715e)

<img width="346" alt="image" src="https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/1173416/18965bf4-955b-46e3-bc34-2a20b0799564">

2024-03-09 02:04 UTC, SgtPooki commented
i've got it down a bit, and normalized some of the output chunk names in [`64335ff` (#97)](https://github.com/ipfs-shipyard/helia-service-worker-gateway/pull/97/commits/64335ffc694cfd345da3a65102c8f58b1b636fbc):

<img width="340" alt="image" src="https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/1173416/89e8c345-237c-4a9a-80a9-d286bccac7cc">

2024-03-11 20:03 UTC, lidel requested changes
`.gz` produced by `CompressionPlugin` are not used, see details below

2024-03-11 20:03 UTC, lidel commented on public/_redirects
> +sw.js /sw.js.gz 301
I am afraid this  `*.gz` regirect business won't work. 
This is not how compression negotiation works on the web. 
These redirects should be removed.

Client sends `Accept-Encoding` with supported compression algorithms, if server supports any of them, it returns `Content-Encoding` header in response to inform client how to decode body.  Redirects are not used in compression negotiation at all.

For prebuilt `.gz` assets to work, you need a reverse proxy to live in front of IPFS gateway, such as nginx with [`gzip_static on`](https://nginx.org/en/docs/http/ngx_http_gzip_static_module.html).

We don't have it enabled anywhere because it triggers an extra IO for every request. 
iirc instead, our infra does compression of plain text filetypes on the fly, and caches result.

2024-03-11 20:03 UTC, lidel commented on webpack.config.js
> +      }
Let's remove `CompressionPlugin` from this project.

We don't benefit from this at all, requires extra configuration ([`gzip_static on`](https://nginx.org/en/docs/http/ngx_http_gzip_static_module.html)), and these unused `.gz` files only makes pinned DAG bigger. 

FYSA gzip compression already works, but it happens outside gateway, on the load balances / reverse proxies in front of it:

```console
$ curl -D - -o /dev/null https://inbrowser.link/ -v --compressed
[..]
* [HTTP/2] [1] [accept-encoding: deflate, gzip, zstd]
[..]
< content-encoding: gzip
```

2024-03-11 22:50 UTC, SgtPooki commented on public/_redirects
> +sw.js /sw.js.gz 301
compression negotiation does work on the web fine with precompressed files.. it just wont work with *our* _redirects without being aware of request headers, which it's not.

understood.

2024-03-11 23:04 UTC, SgtPooki commented
the service worker name is going to change with this:


### On main branch

```
> npm run clean && npm i && npm run build && npx http-server dist

[2024-03-11T22:57:31.489Z]  "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
[2024-03-11T22:57:31.626Z]  "GET /vendor-react.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
[2024-03-11T22:57:31.639Z]  "GET /main.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
[2024-03-11T22:57:31.639Z]  "GET /sw.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
[2024-03-11T22:57:31.783Z]  "GET /favicon.ico" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
[2024-03-11T22:57:31.946Z]  "GET /favicon.ico" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
[2024-03-11T22:57:31.970Z]  "GET /519.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
```

#### Service worker source from chrome devtools

<img width="686" alt="image" src="https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/1173416/49426c4f-173a-4793-acab-8098fd83be2f">



### on this branch

```
> npm run clean && npm run build && npx http-server dist

http-server settings:
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none

Available on:
  http://127.0.0.1:8080
  http://192.168.1.227:8080
Hit CTRL-C to stop the server

# Load the site in browser...


[2024-03-11T23:02:30.242Z]  "GET /519.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
(node:91351) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
[2024-03-11T23:02:30.256Z]  "GET /519.js" Error (404): "Not found"
[2024-03-11T23:03:35.909Z]  "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
[2024-03-11T23:03:36.064Z]  "GET /vendor-react.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
[2024-03-11T23:03:36.070Z]  "GET /main.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
[2024-03-11T23:03:36.070Z]  "GET /vendor-rest.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
[2024-03-11T23:03:36.202Z]  "GET /favicon.ico" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
[2024-03-11T23:03:36.351Z]  "GET /favicon.ico" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
[2024-03-11T23:03:36.377Z]  "GET /sw.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
[2024-03-11T23:03:36.391Z]  "GET /vendor-rest.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
[2024-03-11T23:03:36.574Z]  "GET /sw.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
```

#### Service worker source from chrome devtools

<img width="717" alt="image" src="https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/1173416/010ac901-ea83-4a7b-a671-9942a408a519">

2024-03-11 23:40 UTC, SgtPooki reviewed
self review

2024-03-11 23:40 UTC, SgtPooki commented on src/service-worker-utils.ts
> +  const swRegistration = await navigator.serviceWorker.register(new URL(/* webpackChunkName: "sw" */'sw.ts', import.meta.url))
name is prefixed in webpack config

2024-03-11 23:40 UTC, SgtPooki commented on src/sw.ts
> +async function getVerifiedFetch (): Promise<VerifiedFetch> {
moved in here because nothing else is using it

2024-03-11 23:40 UTC, SgtPooki commented on webpack.config.js
> +  enforceSizeThreshold: 1024,
most of these are defaults

2024-03-11 23:40 UTC, SgtPooki commented on webpack.config.js
> +    filename: 'ipfs-sw-[name].js'
dev and prod build produce the same assets now

2024-03-11 23:42 UTC, SgtPooki commented
final build output:

<img width="342" alt="image" src="https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/1173416/f3f9aa7c-4522-4d9f-8f8b-98860e647537">

<img width="342" alt="image" src="https://github.com/ipfs-shipyard/helia-service-worker-gateway/assets/1173416/343e7016-859f-4593-adcd-ab14d0f3e169">

note that we are no longer creating pre-compressed gzip assets, but webpack bundle analyzer gives us it's guess at what that size would be.

2024-03-11 23:44 UTC, merged